{% set name = "shandy-sqlfmt" %}
{% set version = "0.28.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shandy_sqlfmt-{{ version }}.tar.gz
  sha256: b3a3f2d7ceb3146e33a24269e90916cbee0b0543019b9435c1dbe1984412b83c

build:
  entry_points:
    - sqlfmt = sqlfmt.cli:sqlfmt
    - sqlfmt_primer = sqlfmt_primer.primer:sqlfmt_primer
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - jinja2 >=3.0,<4
    - python >={{ python_min }},<4.0.0
    - click >=8.1,<8.2
    - tqdm >=4.67,<5
    - platformdirs >=2.4,<5.0
    - backports.cached-property >=1.0.2,<2.0.0
    - importlib-metadata >=8.0,<9
    - tomli >=2.0.0,<3.0.0
  run_constrained:
    - black *
    - gitpython >=3.1.24,<4.0.0

test:
  imports:
    - sqlfmt
  commands:
    - pip check
    - sqlfmt --help
    # Don't test sqlfmt_primer as it requires some extras
    # Re-add once we make this a multiple output recipe.
    # - sqlfmt_primer --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://sqlfmt.com
  summary: sqlfmt is an opinionated CLI tool that formats your sql files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
