{% set name = "shandy-sqlfmt" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shandy_sqlfmt-{{ version }}.tar.gz
  sha256: 6beb5c533f59690792dabaf35aba3fbd763525829ddb08796fe11adbec1f9417

build:
  entry_points:
    - sqlfmt = sqlfmt.cli:sqlfmt
    - sqlfmt_primer = sqlfmt_primer.primer:sqlfmt_primer
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - click >=8.0.0,<9.0.0
    - tqdm >=4.0.0,<5.0.0
    - platformdirs >=2.4,<4.0
    - backports.cached-property >=1.0.2,<2.0.0
    - importlib-metadata *
    - tomli >=2.0.1,<3.0.0
  run_constrained:
    - black *
    - gitpython >=3.1.24,<4.0.0

test:
  imports:
    - sqlfmt
  commands:
    - pip check
    - sqlfmt --help
    # Don't test sqlfmt_primer as it requires some extras
    # Re-add once we make this a multiple output recipe.
    # - sqlfmt_primer --help
  requires:
    - pip

about:
  home: https://sqlfmt.com
  summary: sqlfmt is an opinionated CLI tool that formats your sql files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
